name: Default metrics
on:
  schedule: # Run workflow automatically
    - cron: '0 1 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  push: {branches: ["master", "main"]}

jobs:
  build-default-metrics:
    name: build default metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Shanghai
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

